### ISSUE TITLE
Potential mem leaks (for OpenSSL)

### ISSUE THREAD

**Issue by vaijab** [floragunncom/search-guard-ssl#15] opened 2016-03-30 14:55 UTC
I have noticed that if I have this plugin enabled for transport layer SSL JVM keeps using more and more memory until it gets eventually killed.

I am using these versions: https://github.com/UKHomeOffice/docker-elasticsearch/blob/master/Dockerfile#L9

If I set the following to `false` https://github.com/UKHomeOffice/docker-elasticsearch/blob/master/config/elasticsearch.yml#L27 memory usage does not grow.

**Comment by floragunncom** [comment] 2016-03-30 15:36
does this also happen when you do not use openssl?

change line 12 in Dockerfile to
<pre>RUN /elasticsearch/bin/plugin install com.floragunn/search-guard-ssl/2.2.1.7</pre>

and remove openssl and apr from line 4 in Dockerfile

**Comment by floragunncom** [comment] 2016-03-30 18:42
After looking on the SG SSL plugin with a profiler i could identify a memory leak. 

Can you pls. give more details about what you are doing to get a out of memory error and how long it does take until a oom occurs. What is the value of ES_HEAP_SIZE, i think 450m is very minimal so try increase that value. Is ulimit configured properly inside docker?

**Comment by turp1twin** [comment] 2016-03-30 18:44
You could identify a memory leak? Where in the code did you find the leak? Thanks!

**Comment by floragunncom** [comment] 2016-03-30 18:45
up, sorry, i mean "not identify" - will correct the post above

**Comment by vaijab** [comment] 2016-03-31 12:01
@floragunncom 
> does this also happen when you do not use openssl?
Nope. I did what you suggested to disable openssl and I no longer see mem leaks. While previously memory usage would ramp up very quickly.

**Comment by floragunncom** [comment] 2016-05-06 11:54
if you face this issue we recommend for now (as a workaround) to switch off OpenSSL by configuring the following options in elasticsearch.yml on all nodes:

<pre>
searchguard.ssl.transport.enable_openssl_if_available: false
searchguard.ssl.http.enable_openssl_if_available: false
</pre>

We are investigating this currently ...

**Comment by floragunncom** [comment] 2016-05-11 12:15
https://github.com/netty/netty/issues/5235

**Comment by floragunncom** [comment] 2016-05-11 12:19
@vaijab could you try if its working with oracle java 8 together with openssl?

**Comment by vaijab** [comment] 2016-05-12 13:58
@floragunncom I use java 8 already:
```
# java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**Comment by floragunncom** [comment] 2016-05-12 14:12
How many memory you have assigned to your docker container (1GB if i looked correctly)?
Whats you open ssl version?

**Comment by vaijab** [comment] 2016-05-12 14:15
I tried giving it more than 4GB or memory as well.

```
# openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by floragunncom** [comment] 2016-05-26 10:45
Can you provide steps to reproduce this without the need to set up a kubernetes cluster 
(Best would be to reproduce even outside a docker container).

**Comment by softmetz** [comment] 2016-05-26 15:50
I encounter the same bug. I installed sg-ssl with dynamic linked openssl on CentOS 7. Memory grows until OOM killer gets elasticsearch.

The doc references Fork15 of tcnative. There are newer versions. Any reason why I should stick to the old version? Perhaps that fixes the leak?

**Comment by softmetz** [comment] 2016-05-26 15:54
Not sure, but it also might have started, after I set heapspace up to 50% of the system, but since I am still playing around I might also have to have restarted to early. :)

**Comment by floragunncom** [comment] 2016-05-26 16:52
@softmetz what do your environment look like? 
- Baremetal, VM or Docker? How many machines for you ES cluster
- Total memory of the machine or container
- Java Version and Openssl Version
- Java flags (especially -Xmx and -Xms)
- What do you do with elasticsearch and how long does it take before you see the OOM
- Can you try if static linked openssl will work -> https://github.com/floragunncom/search-guard-ssl/wiki/Open-SSL-setup

@vaijab does static linked openssl work for you? see https://github.com/floragunncom/search-guard-ssl/wiki/Open-SSL-setup

**Comment by softmetz** [comment] 2016-05-27 07:08
@floragunncom 

- VM (KVM) with 2 Nodes
- 7823M total RAM / ES_HEAP_SIZE=3912m
- jdk1.8.0_91 (Oracle)
- openssl 1.0.1e-51.el7_2.5
- -Xms3912m -Xmx3912m -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true
- It takes about an hour or two. mlockall makes things happen faster because less memory is available outside the heap. swappiness is set to 1 ( was standard before) but still it uses all (2G) swap.
- ES processes system logs from rsyslog-elasticsearch from 5 hosts (low traffic)

**Comment by softmetz** [comment] 2016-05-27 07:10
@floragunncom  After disabling openssl it ran for the night and memory usage is the same as after start (mlockall is active).

**Comment by floragunncom** [comment] 2016-06-01 08:40
@vaijab @softmetz can you pls check if the problem is solved with 2.3.3.10 version?

**Comment by softmetz** [comment] 2016-06-01 12:01
@floragunncom I upgraded my cluster to 2.3.3 wich worked fine. After enabling openssl (on one node, the other runs on JCE) I get no more connection but this entry in the log:

> [2016-06-01 13:52:37,546][ERROR][com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport] [example.com] SSL Problem error:140D9115:SSL routines:SSL_GET_PREV_SESSION:session id context uninitialized
javax.net.ssl.SSLHandshakeException: error:140D9115:SSL routines:SSL_GET_PREV_SESSION:session id context uninitialized
        at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:575)
        at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:778)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:733)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:810)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:853)
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I still use the Fork15-Version of tcnative, if that helps.

**Comment by floragunncom** [comment] 2016-06-01 13:05
do you get this when you connect via https or is it related to inter cluster communication (and does the openssl node join the cluster properly)?

**Comment by floragunncom** [comment] 2016-06-01 13:06
this is related to https://github.com/netty/netty/issues/5320 i guess

**Comment by softmetz** [comment] 2016-06-01 16:07
@floragunncom  It happens on https-usage. Inter cluster communication works like charm with openssl.

**Comment by floragunncom** [comment] 2016-06-01 20:18
pls try setting ``searchguard.ssl.http.clientauth_mode: NONE`` (just for now)

``error:140D9115:SSL routines:SSL_GET_PREV_SESSION:session id context uninitialized`` is a know issue but i like to get the memory leak fixed first.

**Comment by softmetz** [comment] 2016-06-02 10:25
@floragunncom ok, setting clientauth_mode makes it working again. Now waiting for memory leak to happen.

**Comment by floragunncom** [comment] 2016-06-03 06:02
@vaijab maybe you also want to check if mem leak is solved in 2.3.3.10

**Comment by vaijab** [comment] 2016-06-03 07:10
@floragunncom I will as soon as I get a chance. Thanks!

**Comment by softmetz** [comment] 2016-06-06 09:12
@floragunncom After 5 days the memory usage is ~ 1% above the startup value (mlockall).

**Comment by floragunncom** [comment] 2016-06-06 09:25
@softmetz so the issue seems resolved for you with beta3?

**Comment by softmetz** [comment] 2016-06-06 09:52
@floragunncom If  2.3.3.10 is beta3 for you, yes it seems so. Still there is the issue with 

`searchguard.ssl.http.clientauth_mode: NONE`

Shall I open another issue for this?

**Comment by floragunncom** [comment] 2016-06-06 10:46
@softmetz sorry, meant 2.3.3.10 (beta 3 is the current Search Guard version). You can open an issue albeit its a already known issue. It will be fixed with netty 4.0.37

**Comment by floragunncom** [comment] 2016-06-07 22:21
@softmetz https://github.com/floragunncom/search-guard-ssl/commit/41cb98bd14e46c77061de111fad9b816df1cb63e should fix the [clientauth issue](https://github.com/floragunncom/search-guard-ssl/issues/15#issuecomment-222971818)

**Comment by floragunncom** [comment] 2016-06-07 22:22
@softmetz @vaijab i close this issue for now because it seems to be resolved with 2.3.3.10. If not pls. feel free to reopen it or file another one.

**Closed by floragunncom** 2016-06-07 22:22 UTC

**Comment by vaijab** [comment] 2016-06-08 06:57
@floragunncom thanks a lot!

**Comment by softmetz** [comment] 2016-06-10 20:17
@floragunncom Thanks for providing the fix!

**Comment by vaijab** [comment] 2016-10-05 20:09
So unfortunately, I am seeing mem leaks again while using version v2.4.1.16 with ES v2.4.1. I just basically had to disable TLS, because my ES cluster kept falling over. Master nodes just kept running out of heap space.

**Comment by floragunncom** [comment] 2016-10-05 21:40
Which was the last version that worked for you?

**Comment by floragunncom** [comment] 2016-10-06 09:00
Can you try ``com.floragunn/search-guard-ssl/2.3.4.16`` ?

**Comment by vaijab** [comment] 2016-10-06 16:44
I was using https://github.com/UKHomeOffice/docker-elasticsearch/releases/tag/v0.8.0-rc2 before, but the cluster was not stable either. I now disabled SG SSL entirely and my cluster is rock solid. Cluster discovery is super quick and nodes do not time out anymore.

**Comment by floragunncom** [comment] 2016-10-08 22:19
after a lot of testing i am not able to reproduce. Can you try https://github.com/floragunncom/searchguard-docker-demo and see if you get OOM with this?

Just download or clone and execute ``./build_and_run.sh``
